/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AffiliateSearchMeta', 'model/AffiliateSearchResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AffiliateSearchMeta'), require('./AffiliateSearchResult'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.AffiliateSearchResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.AffiliateSearchMeta, root.AmadeusTravelInnovationSandbox.AffiliateSearchResult);
  }
}(this, function(ApiClient, AffiliateSearchMeta, AffiliateSearchResult) {
  'use strict';




  /**
   * The AffiliateSearchResponse model module.
   * @module model/AffiliateSearchResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>AffiliateSearchResponse</code>.
   * @alias module:model/AffiliateSearchResponse
   * @class
   * @param meta {module:model/AffiliateSearchMeta} Meta data about the results
   */
  var exports = function(meta) {
    var _this = this;

    _this['meta'] = meta;

  };

  /**
   * Constructs a <code>AffiliateSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AffiliateSearchResponse} obj Optional instance to populate.
   * @return {module:model/AffiliateSearchResponse} The populated <code>AffiliateSearchResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('meta')) {
        obj['meta'] = AffiliateSearchMeta.constructFromObject(data['meta']);
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [AffiliateSearchResult]);
      }
    }
    return obj;
  }

  /**
   * Meta data about the results
   * @member {module:model/AffiliateSearchMeta} meta
   */
  exports.prototype['meta'] = undefined;
  /**
   * @member {Array.<module:model/AffiliateSearchResult>} results
   */
  exports.prototype['results'] = undefined;



  return exports;
}));


