/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Company', 'model/Geolocation', 'model/Vehicle'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Company'), require('./Geolocation'), require('./Vehicle'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.CarSearchResult = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Company, root.AmadeusTravelInnovationSandbox.Geolocation, root.AmadeusTravelInnovationSandbox.Vehicle);
  }
}(this, function(ApiClient, Company, Geolocation, Vehicle) {
  'use strict';




  /**
   * The CarSearchResult model module.
   * @module model/CarSearchResult
   * @version 1.2
   */

  /**
   * Constructs a new <code>CarSearchResult</code>.
   * @alias module:model/CarSearchResult
   * @class
   * @param provider {module:model/Company} Details of the car company offering this rental.
   */
  var exports = function(provider) {
    var _this = this;

    _this['provider'] = provider;



  };

  /**
   * Constructs a <code>CarSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarSearchResult} obj Optional instance to populate.
   * @return {module:model/CarSearchResult} The populated <code>CarSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('provider')) {
        obj['provider'] = Company.constructFromObject(data['provider']);
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = Geolocation.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('airport')) {
        obj['airport'] = ApiClient.convertToType(data['airport'], 'String');
      }
      if (data.hasOwnProperty('cars')) {
        obj['cars'] = ApiClient.convertToType(data['cars'], [Vehicle]);
      }
    }
    return obj;
  }

  /**
   * Details of the car company offering this rental.
   * @member {module:model/Company} provider
   */
  exports.prototype['provider'] = undefined;
  /**
   * This car rental company's approximate geolocation. The exact quality of this parameter depends on the provider but it's usually quite accurate.
   * @member {module:model/Geolocation} location
   */
  exports.prototype['location'] = undefined;
  /**
   * The exact quality of this parameter depends on the provider but it's usually quite accurate.
   * @member {String} airport
   */
  exports.prototype['airport'] = undefined;
  /**
   * Further details about each of the vehicles offered by this car rental provider.
   * @member {Array.<module:model/Vehicle>} cars
   */
  exports.prototype['cars'] = undefined;



  return exports;
}));


