/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.FareRestrictions = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FareRestrictions model module.
   * @module model/FareRestrictions
   * @version 1.2
   */

  /**
   * Constructs a new <code>FareRestrictions</code>.
   * @alias module:model/FareRestrictions
   * @class
   * @param refundable {Boolean} Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply
   * @param changePenalties {Boolean} Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply
   */
  var exports = function(refundable, changePenalties) {
    var _this = this;

    _this['refundable'] = refundable;
    _this['change_penalties'] = changePenalties;
  };

  /**
   * Constructs a <code>FareRestrictions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FareRestrictions} obj Optional instance to populate.
   * @return {module:model/FareRestrictions} The populated <code>FareRestrictions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('refundable')) {
        obj['refundable'] = ApiClient.convertToType(data['refundable'], 'Boolean');
      }
      if (data.hasOwnProperty('change_penalties')) {
        obj['change_penalties'] = ApiClient.convertToType(data['change_penalties'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply
   * @member {Boolean} refundable
   */
  exports.prototype['refundable'] = undefined;
  /**
   * Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply
   * @member {Boolean} change_penalties
   */
  exports.prototype['change_penalties'] = undefined;



  return exports;
}));


