/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlightSearchBound'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlightSearchBound'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.FlightSearchItinerary = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.FlightSearchBound);
  }
}(this, function(ApiClient, FlightSearchBound) {
  'use strict';




  /**
   * The FlightSearchItinerary model module.
   * @module model/FlightSearchItinerary
   * @version 1.2
   */

  /**
   * Constructs a new <code>FlightSearchItinerary</code>.
   * @alias module:model/FlightSearchItinerary
   * @class
   * @param outbound {module:model/FlightSearchBound} The bound container for the flight information for bringing the traveler from the origin airport to the destination airport
   */
  var exports = function(outbound) {
    var _this = this;

    _this['outbound'] = outbound;

  };

  /**
   * Constructs a <code>FlightSearchItinerary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlightSearchItinerary} obj Optional instance to populate.
   * @return {module:model/FlightSearchItinerary} The populated <code>FlightSearchItinerary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('outbound')) {
        obj['outbound'] = FlightSearchBound.constructFromObject(data['outbound']);
      }
      if (data.hasOwnProperty('inbound')) {
        obj['inbound'] = FlightSearchBound.constructFromObject(data['inbound']);
      }
    }
    return obj;
  }

  /**
   * The bound container for the flight information for bringing the traveler from the origin airport to the destination airport
   * @member {module:model/FlightSearchBound} outbound
   */
  exports.prototype['outbound'] = undefined;
  /**
   * The bound container for the flight information for bringing the traveler from the destination airport to the origin airport
   * @member {module:model/FlightSearchBound} inbound
   */
  exports.prototype['inbound'] = undefined;



  return exports;
}));


