/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlightTrafficSearchResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlightTrafficSearchResult'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.FlightTrafficSearchResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.FlightTrafficSearchResult);
  }
}(this, function(ApiClient, FlightTrafficSearchResult) {
  'use strict';




  /**
   * The FlightTrafficSearchResponse model module.
   * @module model/FlightTrafficSearchResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>FlightTrafficSearchResponse</code>.
   * @alias module:model/FlightTrafficSearchResponse
   * @class
   * @param period {String} The date period, in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format YYYY-MM or YYYY
   * @param origin {String} <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a>
   * @param results {Array.<module:model/FlightTrafficSearchResult>} 
   */
  var exports = function(period, origin, results) {
    var _this = this;

    _this['period'] = period;
    _this['origin'] = origin;
    _this['results'] = results;
  };

  /**
   * Constructs a <code>FlightTrafficSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlightTrafficSearchResponse} obj Optional instance to populate.
   * @return {module:model/FlightTrafficSearchResponse} The populated <code>FlightTrafficSearchResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('period')) {
        obj['period'] = ApiClient.convertToType(data['period'], 'String');
      }
      if (data.hasOwnProperty('origin')) {
        obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [FlightTrafficSearchResult]);
      }
    }
    return obj;
  }

  /**
   * The date period, in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format YYYY-MM or YYYY
   * @member {String} period
   */
  exports.prototype['period'] = undefined;
  /**
   * <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a>
   * @member {String} origin
   */
  exports.prototype['origin'] = undefined;
  /**
   * @member {Array.<module:model/FlightTrafficSearchResult>} results
   */
  exports.prototype['results'] = undefined;



  return exports;
}));


