/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.FlightReservationBookingInfo = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FlightReservationBookingInfo model module.
   * @module model/FlightReservationBookingInfo
   * @version 1.2
   */

  /**
   * Constructs a new <code>FlightReservationBookingInfo</code>.
   * @alias module:model/FlightReservationBookingInfo
   * @class
   * @param travelClass {String} The cabin class offered on this flight. An enumeration that will read either ECONOMY, PREMIUM_ECONOMY, BUSINESS or FIRST
   * @param bookingCode {String} The Reservation Booking Designator code that determines the quality and terms of the flight offered for the given price. A single letter from A..Z
   * @param airlineRecordLocator {String} 6 character identifier of this travel record on the airline's system. May be the same as the global record locator.
   * @param status {String} An enumeration to represent the reservation status for this seat on this flight. For example&colon; CONFIRMED, CANCELLED, RESCHEDULED, FLIGHT_CANCELLED, WAITLISTED.
   */
  var exports = function(travelClass, bookingCode, airlineRecordLocator, status) {
    var _this = this;

    _this['travel_class'] = travelClass;
    _this['booking_code'] = bookingCode;
    _this['airline_record_locator'] = airlineRecordLocator;
    _this['status'] = status;
  };

  /**
   * Constructs a <code>FlightReservationBookingInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlightReservationBookingInfo} obj Optional instance to populate.
   * @return {module:model/FlightReservationBookingInfo} The populated <code>FlightReservationBookingInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('travel_class')) {
        obj['travel_class'] = ApiClient.convertToType(data['travel_class'], 'String');
      }
      if (data.hasOwnProperty('booking_code')) {
        obj['booking_code'] = ApiClient.convertToType(data['booking_code'], 'String');
      }
      if (data.hasOwnProperty('airline_record_locator')) {
        obj['airline_record_locator'] = ApiClient.convertToType(data['airline_record_locator'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * The cabin class offered on this flight. An enumeration that will read either ECONOMY, PREMIUM_ECONOMY, BUSINESS or FIRST
   * @member {String} travel_class
   */
  exports.prototype['travel_class'] = undefined;
  /**
   * The Reservation Booking Designator code that determines the quality and terms of the flight offered for the given price. A single letter from A..Z
   * @member {String} booking_code
   */
  exports.prototype['booking_code'] = undefined;
  /**
   * 6 character identifier of this travel record on the airline's system. May be the same as the global record locator.
   * @member {String} airline_record_locator
   */
  exports.prototype['airline_record_locator'] = undefined;
  /**
   * An enumeration to represent the reservation status for this seat on this flight. For example&colon; CONFIRMED, CANCELLED, RESCHEDULED, FLIGHT_CANCELLED, WAITLISTED.
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


