/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.FrequentTravelerCard = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FrequentTravelerCard model module.
   * @module model/FrequentTravelerCard
   * @version 1.2
   */

  /**
   * Constructs a new <code>FrequentTravelerCard</code>.
   * @alias module:model/FrequentTravelerCard
   * @class
   * @param issuerType {String} The type of organization that issued the card. This is an enumeration, possible values are AIRLINE, HOTEL_CHAIN, RENTAL_CAR_PROVIDER, RAILWAY.
   * @param companyCode {String} The identifying code of the issuer, within the context of its type. For example&colon; BA (and if the issuer type is AIRLINE, this indicates BA=British Airways).
   * @param cardNumber {String} The identifying number (or string) marked on the card. For example&colon; 12345678.
   */
  var exports = function(issuerType, companyCode, cardNumber) {
    var _this = this;

    _this['issuer_type'] = issuerType;
    _this['company_code'] = companyCode;
    _this['card_number'] = cardNumber;
  };

  /**
   * Constructs a <code>FrequentTravelerCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FrequentTravelerCard} obj Optional instance to populate.
   * @return {module:model/FrequentTravelerCard} The populated <code>FrequentTravelerCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('issuer_type')) {
        obj['issuer_type'] = ApiClient.convertToType(data['issuer_type'], 'String');
      }
      if (data.hasOwnProperty('company_code')) {
        obj['company_code'] = ApiClient.convertToType(data['company_code'], 'String');
      }
      if (data.hasOwnProperty('card_number')) {
        obj['card_number'] = ApiClient.convertToType(data['card_number'], 'String');
      }
    }
    return obj;
  }

  /**
   * The type of organization that issued the card. This is an enumeration, possible values are AIRLINE, HOTEL_CHAIN, RENTAL_CAR_PROVIDER, RAILWAY.
   * @member {String} issuer_type
   */
  exports.prototype['issuer_type'] = undefined;
  /**
   * The identifying code of the issuer, within the context of its type. For example&colon; BA (and if the issuer type is AIRLINE, this indicates BA=British Airways).
   * @member {String} company_code
   */
  exports.prototype['company_code'] = undefined;
  /**
   * The identifying number (or string) marked on the card. For example&colon; 12345678.
   * @member {String} card_number
   */
  exports.prototype['card_number'] = undefined;



  return exports;
}));


