/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.Geolocation = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Geolocation model module.
   * @module model/Geolocation
   * @version 1.2
   */

  /**
   * Constructs a new <code>Geolocation</code>.
   * An object to describe the coordinates of a map location
   * @alias module:model/Geolocation
   * @class
   * @param latitude {Number} The north-south coordinate of this location, in decimal degrees, between -90 and 90
   * @param longitude {Number} The east-west coordinate of this location, in decimal degrees, between -180 and 180
   */
  var exports = function(latitude, longitude) {
    var _this = this;

    _this['latitude'] = latitude;
    _this['longitude'] = longitude;

  };

  /**
   * Constructs a <code>Geolocation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Geolocation} obj Optional instance to populate.
   * @return {module:model/Geolocation} The populated <code>Geolocation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('google_maps_link')) {
        obj['google_maps_link'] = ApiClient.convertToType(data['google_maps_link'], 'String');
      }
    }
    return obj;
  }

  /**
   * The north-south coordinate of this location, in decimal degrees, between -90 and 90
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * The east-west coordinate of this location, in decimal degrees, between -180 and 180
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * For YapQ APIs only  - a link to a google map rendering of this location.
   * @member {String} google_maps_link
   */
  exports.prototype['google_maps_link'] = undefined;



  return exports;
}));


