/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/Amenity', 'model/Amount', 'model/Award', 'model/Contact', 'model/Geolocation', 'model/HotelRoom', 'model/Image', 'model/Link'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Address'), require('./Amenity'), require('./Amount'), require('./Award'), require('./Contact'), require('./Geolocation'), require('./HotelRoom'), require('./Image'), require('./Link'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.HotelPropertyResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Address, root.AmadeusTravelInnovationSandbox.Amenity, root.AmadeusTravelInnovationSandbox.Amount, root.AmadeusTravelInnovationSandbox.Award, root.AmadeusTravelInnovationSandbox.Contact, root.AmadeusTravelInnovationSandbox.Geolocation, root.AmadeusTravelInnovationSandbox.HotelRoom, root.AmadeusTravelInnovationSandbox.Image, root.AmadeusTravelInnovationSandbox.Link);
  }
}(this, function(ApiClient, Address, Amenity, Amount, Award, Contact, Geolocation, HotelRoom, Image, Link) {
  'use strict';




  /**
   * The HotelPropertyResponse model module.
   * @module model/HotelPropertyResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>HotelPropertyResponse</code>.
   * @alias module:model/HotelPropertyResponse
   * @class
   * @param propertyCode {String} The 8 character property code of this given hotel. The first 2 characters of this code are the chain code that can be specified in the input. The remaining elements are proprietary to each hotel chain.
   * @param propertyName {String} The name of this hotel.
   * @param location {module:model/Geolocation} 
   * @param totalPrice {module:model/Amount} The lowest price of a stay, from the given check in date to the given check out date.
   * @param minDailyRate {module:model/Amount} The lowest price per day that the hotel offers between the given check-in and check-out dates. Extra taxes may apply to this rate.
   */
  var exports = function(propertyCode, propertyName, location, totalPrice, minDailyRate) {
    var _this = this;

    _this['property_code'] = propertyCode;
    _this['property_name'] = propertyName;
    _this['location'] = location;

    _this['total_price'] = totalPrice;
    _this['min_daily_rate'] = minDailyRate;






  };

  /**
   * Constructs a <code>HotelPropertyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HotelPropertyResponse} obj Optional instance to populate.
   * @return {module:model/HotelPropertyResponse} The populated <code>HotelPropertyResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('property_code')) {
        obj['property_code'] = ApiClient.convertToType(data['property_code'], 'String');
      }
      if (data.hasOwnProperty('property_name')) {
        obj['property_name'] = ApiClient.convertToType(data['property_name'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = Geolocation.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = Address.constructFromObject(data['address']);
      }
      if (data.hasOwnProperty('total_price')) {
        obj['total_price'] = Amount.constructFromObject(data['total_price']);
      }
      if (data.hasOwnProperty('min_daily_rate')) {
        obj['min_daily_rate'] = Amount.constructFromObject(data['min_daily_rate']);
      }
      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = ApiClient.convertToType(data['contacts'], [Contact]);
      }
      if (data.hasOwnProperty('amenities')) {
        obj['amenities'] = ApiClient.convertToType(data['amenities'], [Amenity]);
      }
      if (data.hasOwnProperty('awards')) {
        obj['awards'] = ApiClient.convertToType(data['awards'], [Award]);
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], [Image]);
      }
      if (data.hasOwnProperty('rooms')) {
        obj['rooms'] = ApiClient.convertToType(data['rooms'], [HotelRoom]);
      }
      if (data.hasOwnProperty('more_rooms_at_this_hotel')) {
        obj['more_rooms_at_this_hotel'] = Link.constructFromObject(data['more_rooms_at_this_hotel']);
      }
    }
    return obj;
  }

  /**
   * The 8 character property code of this given hotel. The first 2 characters of this code are the chain code that can be specified in the input. The remaining elements are proprietary to each hotel chain.
   * @member {String} property_code
   */
  exports.prototype['property_code'] = undefined;
  /**
   * The name of this hotel.
   * @member {String} property_name
   */
  exports.prototype['property_name'] = undefined;
  /**
   * @member {module:model/Geolocation} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {module:model/Address} address
   */
  exports.prototype['address'] = undefined;
  /**
   * The lowest price of a stay, from the given check in date to the given check out date.
   * @member {module:model/Amount} total_price
   */
  exports.prototype['total_price'] = undefined;
  /**
   * The lowest price per day that the hotel offers between the given check-in and check-out dates. Extra taxes may apply to this rate.
   * @member {module:model/Amount} min_daily_rate
   */
  exports.prototype['min_daily_rate'] = undefined;
  /**
   * An array of contact objects to tell the user how to contact the hotel. Typically includes a phone and fax number
   * @member {Array.<module:model/Contact>} contacts
   */
  exports.prototype['contacts'] = undefined;
  /**
   * An array of amenity objects to the user what facilities this hotel might provide, such as a pool or parking.  If this array is empty, it does not necessarily mean that there are no amenities available at this hotel, it could also mean that the hotel does not list their amenities in our search! 
   * @member {Array.<module:model/Amenity>} amenities
   */
  exports.prototype['amenities'] = undefined;
  /**
   * An array of hotel award objects to give the user an expectation of the service quality at this hotel. This can be used to indicate, for example, the star rating of a hotel. If this array is empty, it does not necessarily mean that the hotel has no awards, it could simply mean that they didn't tell us about them!
   * @member {Array.<module:model/Award>} awards
   */
  exports.prototype['awards'] = undefined;
  /**
   * A selection of image objects, showing pictures of the hotel building, the entrance or some rooms, to give an indication of what to expect at this hotel. Note that redistribution of images outside Amadeus products requires licensing from our image providers: Leonardo and Ice Portal. Thus image links are returned for whitelisted Amadeus users only.
   * @member {Array.<module:model/Image>} images
   */
  exports.prototype['images'] = undefined;
  /**
   * Information on currently available rooms at this hotel.
   * @member {Array.<module:model/HotelRoom>} rooms
   */
  exports.prototype['rooms'] = undefined;
  /**
   * Provides a ready-to-use link to make a follow up request to find more available rooms at this hotel
   * @member {module:model/Link} more_rooms_at_this_hotel
   */
  exports.prototype['more_rooms_at_this_hotel'] = undefined;



  return exports;
}));


