/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount', 'model/PeriodRate', 'model/RoomInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'), require('./PeriodRate'), require('./RoomInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.HotelRoom = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Amount, root.AmadeusTravelInnovationSandbox.PeriodRate, root.AmadeusTravelInnovationSandbox.RoomInfo);
  }
}(this, function(ApiClient, Amount, PeriodRate, RoomInfo) {
  'use strict';




  /**
   * The HotelRoom model module.
   * @module model/HotelRoom
   * @version 1.2
   */

  /**
   * Constructs a new <code>HotelRoom</code>.
   * @alias module:model/HotelRoom
   * @class
   * @param bookingCode {String} The booking code identifies a product at the hotel. It can be used to book a room.
   */
  var exports = function(bookingCode) {
    var _this = this;

    _this['booking_code'] = bookingCode;







  };

  /**
   * Constructs a <code>HotelRoom</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HotelRoom} obj Optional instance to populate.
   * @return {module:model/HotelRoom} The populated <code>HotelRoom</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('booking_code')) {
        obj['booking_code'] = ApiClient.convertToType(data['booking_code'], 'String');
      }
      if (data.hasOwnProperty('room_type_code')) {
        obj['room_type_code'] = ApiClient.convertToType(data['room_type_code'], 'String');
      }
      if (data.hasOwnProperty('rate_plan_code')) {
        obj['rate_plan_code'] = ApiClient.convertToType(data['rate_plan_code'], 'String');
      }
      if (data.hasOwnProperty('total_amount')) {
        obj['total_amount'] = Amount.constructFromObject(data['total_amount']);
      }
      if (data.hasOwnProperty('rates')) {
        obj['rates'] = ApiClient.convertToType(data['rates'], [PeriodRate]);
      }
      if (data.hasOwnProperty('descriptions')) {
        obj['descriptions'] = ApiClient.convertToType(data['descriptions'], ['String']);
      }
      if (data.hasOwnProperty('room_type_info')) {
        obj['room_type_info'] = RoomInfo.constructFromObject(data['room_type_info']);
      }
      if (data.hasOwnProperty('rate_type_code')) {
        obj['rate_type_code'] = ApiClient.convertToType(data['rate_type_code'], 'String');
      }
    }
    return obj;
  }

  /**
   * The booking code identifies a product at the hotel. It can be used to book a room.
   * @member {String} booking_code
   */
  exports.prototype['booking_code'] = undefined;
  /**
   * A 3-letter code to identify a specific room type.
   * @member {String} room_type_code
   */
  exports.prototype['room_type_code'] = undefined;
  /**
   * A 3 letter code to designate different rates base on traveler type.
   * @member {String} rate_plan_code
   */
  exports.prototype['rate_plan_code'] = undefined;
  /**
   * The total price of staying in this room from the given check-in date to the given check-out date
   * @member {module:model/Amount} total_amount
   */
  exports.prototype['total_amount'] = undefined;
  /**
   * The total price of staying in this room from the given check-in date to the given check-out date
   * @member {Array.<module:model/PeriodRate>} rates
   */
  exports.prototype['rates'] = undefined;
  /**
   * An array of description strings describing room and rate types features
   * @member {Array.<String>} descriptions
   */
  exports.prototype['descriptions'] = undefined;
  /**
   * @member {module:model/RoomInfo} room_type_info
   */
  exports.prototype['room_type_info'] = undefined;
  /**
   * The unique rate code used by the hotel chain to price this room's rate
   * @member {String} rate_type_code
   */
  exports.prototype['rate_type_code'] = undefined;



  return exports;
}));


