/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount', 'model/HotelReservationBookingInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'), require('./HotelReservationBookingInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.HotelReservation = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Amount, root.AmadeusTravelInnovationSandbox.HotelReservationBookingInfo);
  }
}(this, function(ApiClient, Amount, HotelReservationBookingInfo) {
  'use strict';




  /**
   * The HotelReservation model module.
   * @module model/HotelReservation
   * @version 1.2
   */

  /**
   * Constructs a new <code>HotelReservation</code>.
   * @alias module:model/HotelReservation
   * @class
   * @param id {String} Uniquely identifies this hotel room reservation in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.
   * @param checkIn {Date} Date on which the guest will begin their stay in the hotel, in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-dd.
   * @param checkOut {Date} Date on which the guest will end their stay in the hotel, in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-dd.
   * @param propertyCode {String} The 8 character property code of this given hotel. The first 2 characters of this code are the chain code that can be specified in the input. The remaining elements are proprietary to each hotel chain.
   * @param propertyName {String} The name of this hotel.
   * @param travelerIds {Array.<String>} Traveler identifiers to indicate the travelers to whom this hotel room reservation applies. Generally all non-infant room occupants will be marked in this array.
   * @param bookingInfo {module:model/HotelReservationBookingInfo} Additional details and status of this hotel room reservation.
   */
  var exports = function(id, checkIn, checkOut, propertyCode, propertyName, travelerIds, bookingInfo) {
    var _this = this;

    _this['id'] = id;
    _this['check_in'] = checkIn;
    _this['check_out'] = checkOut;
    _this['property_code'] = propertyCode;
    _this['property_name'] = propertyName;

    _this['traveler_ids'] = travelerIds;
    _this['booking_info'] = bookingInfo;
  };

  /**
   * Constructs a <code>HotelReservation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HotelReservation} obj Optional instance to populate.
   * @return {module:model/HotelReservation} The populated <code>HotelReservation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('check_in')) {
        obj['check_in'] = ApiClient.convertToType(data['check_in'], 'Date');
      }
      if (data.hasOwnProperty('check_out')) {
        obj['check_out'] = ApiClient.convertToType(data['check_out'], 'Date');
      }
      if (data.hasOwnProperty('property_code')) {
        obj['property_code'] = ApiClient.convertToType(data['property_code'], 'String');
      }
      if (data.hasOwnProperty('property_name')) {
        obj['property_name'] = ApiClient.convertToType(data['property_name'], 'String');
      }
      if (data.hasOwnProperty('total_price')) {
        obj['total_price'] = Amount.constructFromObject(data['total_price']);
      }
      if (data.hasOwnProperty('traveler_ids')) {
        obj['traveler_ids'] = ApiClient.convertToType(data['traveler_ids'], ['String']);
      }
      if (data.hasOwnProperty('booking_info')) {
        obj['booking_info'] = HotelReservationBookingInfo.constructFromObject(data['booking_info']);
      }
    }
    return obj;
  }

  /**
   * Uniquely identifies this hotel room reservation in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Date on which the guest will begin their stay in the hotel, in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-dd.
   * @member {Date} check_in
   */
  exports.prototype['check_in'] = undefined;
  /**
   * Date on which the guest will end their stay in the hotel, in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-dd.
   * @member {Date} check_out
   */
  exports.prototype['check_out'] = undefined;
  /**
   * The 8 character property code of this given hotel. The first 2 characters of this code are the chain code that can be specified in the input. The remaining elements are proprietary to each hotel chain.
   * @member {String} property_code
   */
  exports.prototype['property_code'] = undefined;
  /**
   * The name of this hotel.
   * @member {String} property_name
   */
  exports.prototype['property_name'] = undefined;
  /**
   * The total price of this stay, from the given check in date to the given check out date.
   * @member {module:model/Amount} total_price
   */
  exports.prototype['total_price'] = undefined;
  /**
   * Traveler identifiers to indicate the travelers to whom this hotel room reservation applies. Generally all non-infant room occupants will be marked in this array.
   * @member {Array.<String>} traveler_ids
   */
  exports.prototype['traveler_ids'] = undefined;
  /**
   * Additional details and status of this hotel room reservation.
   * @member {module:model/HotelReservationBookingInfo} booking_info
   */
  exports.prototype['booking_info'] = undefined;



  return exports;
}));


