/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Image'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Image'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.ImageSize = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Image);
  }
}(this, function(ApiClient, Image) {
  'use strict';




  /**
   * The ImageSize model module.
   * @module model/ImageSize
   * @version 1.2
   */

  /**
   * Constructs a new <code>ImageSize</code>.
   * An image size selector used in the YapQ API response. The size should correspond the the image_size parameter used during input
   * @alias module:model/ImageSize
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ImageSize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageSize} obj Optional instance to populate.
   * @return {module:model/ImageSize} The populated <code>ImageSize</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('small')) {
        obj['small'] = Image.constructFromObject(data['small']);
      }
      if (data.hasOwnProperty('medium')) {
        obj['medium'] = Image.constructFromObject(data['medium']);
      }
      if (data.hasOwnProperty('large')) {
        obj['large'] = Image.constructFromObject(data['large']);
      }
      if (data.hasOwnProperty('hd')) {
        obj['hd'] = Image.constructFromObject(data['hd']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Image} small
   */
  exports.prototype['small'] = undefined;
  /**
   * @member {module:model/Image} medium
   */
  exports.prototype['medium'] = undefined;
  /**
   * @member {module:model/Image} large
   */
  exports.prototype['large'] = undefined;
  /**
   * @member {module:model/Image} hd
   */
  exports.prototype['hd'] = undefined;



  return exports;
}));


