/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AirportInformation', 'model/CityInformation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AirportInformation'), require('./CityInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.LocationResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.AirportInformation, root.AmadeusTravelInnovationSandbox.CityInformation);
  }
}(this, function(ApiClient, AirportInformation, CityInformation) {
  'use strict';




  /**
   * The LocationResponse model module.
   * @module model/LocationResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>LocationResponse</code>.
   * @alias module:model/LocationResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>LocationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LocationResponse} obj Optional instance to populate.
   * @return {module:model/LocationResponse} The populated <code>LocationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('city')) {
        obj['city'] = CityInformation.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('airports')) {
        obj['airports'] = ApiClient.convertToType(data['airports'], [AirportInformation]);
      }
    }
    return obj;
  }

  /**
   * Information for any <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> of the city which corresponds to the provided code
   * @member {module:model/CityInformation} city
   */
  exports.prototype['city'] = undefined;
  /**
   * Information for any IATA airport located in the provided <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> of the city or which corresponds to the provided code
   * @member {Array.<module:model/AirportInformation>} airports
   */
  exports.prototype['airports'] = undefined;



  return exports;
}));


