/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlightSearchItinerary', 'model/FlightSearchPrice'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlightSearchItinerary'), require('./FlightSearchPrice'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.LowFareSearchResult = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.FlightSearchItinerary, root.AmadeusTravelInnovationSandbox.FlightSearchPrice);
  }
}(this, function(ApiClient, FlightSearchItinerary, FlightSearchPrice) {
  'use strict';




  /**
   * The LowFareSearchResult model module.
   * @module model/LowFareSearchResult
   * @version 1.2
   */

  /**
   * Constructs a new <code>LowFareSearchResult</code>.
   * @alias module:model/LowFareSearchResult
   * @class
   * @param fare {module:model/FlightSearchPrice} The price and fare information which applies to all itineraries in this response
   */
  var exports = function(fare) {
    var _this = this;


    _this['fare'] = fare;
  };

  /**
   * Constructs a <code>LowFareSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LowFareSearchResult} obj Optional instance to populate.
   * @return {module:model/LowFareSearchResult} The populated <code>LowFareSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('itineraries')) {
        obj['itineraries'] = ApiClient.convertToType(data['itineraries'], [FlightSearchItinerary]);
      }
      if (data.hasOwnProperty('fare')) {
        obj['fare'] = FlightSearchPrice.constructFromObject(data['fare']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/FlightSearchItinerary>} itineraries
   */
  exports.prototype['itineraries'] = undefined;
  /**
   * The price and fare information which applies to all itineraries in this response
   * @member {module:model/FlightSearchPrice} fare
   */
  exports.prototype['fare'] = undefined;



  return exports;
}));


