/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LowFareSearchResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LowFareSearchResult'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.LowFareSearchResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.LowFareSearchResult);
  }
}(this, function(ApiClient, LowFareSearchResult) {
  'use strict';




  /**
   * The LowFareSearchResponse model module.
   * @module model/LowFareSearchResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>LowFareSearchResponse</code>.
   * @alias module:model/LowFareSearchResponse
   * @class
   * @param currency {String} <a href=\"http://en.wikipedia.org/wiki/ISO_4217\">ISO 4217</a> currency code.
   */
  var exports = function(currency) {
    var _this = this;

    _this['currency'] = currency;

  };

  /**
   * Constructs a <code>LowFareSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LowFareSearchResponse} obj Optional instance to populate.
   * @return {module:model/LowFareSearchResponse} The populated <code>LowFareSearchResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [LowFareSearchResult]);
      }
    }
    return obj;
  }

  /**
   * <a href=\"http://en.wikipedia.org/wiki/ISO_4217\">ISO 4217</a> currency code.
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {Array.<module:model/LowFareSearchResult>} results
   */
  exports.prototype['results'] = undefined;



  return exports;
}));


