/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Geolocation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Geolocation'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.PointOfInterestCity = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Geolocation);
  }
}(this, function(ApiClient, Geolocation) {
  'use strict';




  /**
   * The PointOfInterestCity model module.
   * @module model/PointOfInterestCity
   * @version 1.2
   */

  /**
   * Constructs a new <code>PointOfInterestCity</code>.
   * @alias module:model/PointOfInterestCity
   * @class
   * @param name {String} The name of the location that was searched for
   * @param location {module:model/Geolocation} 
   * @param totalPointsOfInterest {Integer} The total number of points_of_interest that YapQ has indexed for this city
   */
  var exports = function(name, location, totalPointsOfInterest) {
    var _this = this;

    _this['name'] = name;

    _this['location'] = location;
    _this['total_points_of_interest'] = totalPointsOfInterest;
  };

  /**
   * Constructs a <code>PointOfInterestCity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PointOfInterestCity} obj Optional instance to populate.
   * @return {module:model/PointOfInterestCity} The populated <code>PointOfInterestCity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('geoname_id')) {
        obj['geoname_id'] = ApiClient.convertToType(data['geoname_id'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = Geolocation.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('total_points_of_interest')) {
        obj['total_points_of_interest'] = ApiClient.convertToType(data['total_points_of_interest'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * The name of the location that was searched for
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The Geonames ID of the location that was searched for
   * @member {String} geoname_id
   */
  exports.prototype['geoname_id'] = undefined;
  /**
   * @member {module:model/Geolocation} location
   */
  exports.prototype['location'] = undefined;
  /**
   * The total number of points_of_interest that YapQ has indexed for this city
   * @member {Integer} total_points_of_interest
   */
  exports.prototype['total_points_of_interest'] = undefined;



  return exports;
}));


