/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.PointOfInterestResultGrades = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PointOfInterestResultGrades model module.
   * @module model/PointOfInterestResultGrades
   * @version 1.2
   */

  /**
   * Constructs a new <code>PointOfInterestResultGrades</code>.
   * Result availble grades.
   * @alias module:model/PointOfInterestResultGrades
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PointOfInterestResultGrades</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PointOfInterestResultGrades} obj Optional instance to populate.
   * @return {module:model/PointOfInterestResultGrades} The populated <code>PointOfInterestResultGrades</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('yapq_grade')) {
        obj['yapq_grade'] = ApiClient.convertToType(data['yapq_grade'], 'Integer');
      }
      if (data.hasOwnProperty('city_grade')) {
        obj['city_grade'] = ApiClient.convertToType(data['city_grade'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * Main YAPQ grade. A grade out of 5 for this point, rated against all points in the world and normalized among selected group of points. 5 is best, 0 is worst.
   * @member {Integer} yapq_grade
   */
  exports.prototype['yapq_grade'] = undefined;
  /**
   * The ranking of this point of interest compared to other points in this city. 1 is the highest rated.
   * @member {Integer} city_grade
   */
  exports.prototype['city_grade'] = undefined;



  return exports;
}));


