/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.PointOfInterestDetails = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PointOfInterestDetails model module.
   * @module model/PointOfInterestDetails
   * @version 1.2
   */

  /**
   * Constructs a new <code>PointOfInterestDetails</code>.
   * @alias module:model/PointOfInterestDetails
   * @class
   * @param shortDescription {String} A summary of the given point
   * @param description {String} A paragraph describing this point of interest
   * @param wikiPageLink {String} A link to this point of interest&quot;s wikipedia page
   */
  var exports = function(shortDescription, description, wikiPageLink) {
    var _this = this;

    _this['short_description'] = shortDescription;
    _this['description'] = description;
    _this['wiki_page_link'] = wikiPageLink;
  };

  /**
   * Constructs a <code>PointOfInterestDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PointOfInterestDetails} obj Optional instance to populate.
   * @return {module:model/PointOfInterestDetails} The populated <code>PointOfInterestDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('short_description')) {
        obj['short_description'] = ApiClient.convertToType(data['short_description'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('wiki_page_link')) {
        obj['wiki_page_link'] = ApiClient.convertToType(data['wiki_page_link'], 'String');
      }
    }
    return obj;
  }

  /**
   * A summary of the given point
   * @member {String} short_description
   */
  exports.prototype['short_description'] = undefined;
  /**
   * A paragraph describing this point of interest
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * A link to this point of interest&quot;s wikipedia page
   * @member {String} wiki_page_link
   */
  exports.prototype['wiki_page_link'] = undefined;



  return exports;
}));


