/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.RailStationAutocompleteResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RailStationAutocompleteResponse model module.
   * @module model/RailStationAutocompleteResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>RailStationAutocompleteResponse</code>.
   * @alias module:model/RailStationAutocompleteResponse
   * @class
   * @param value {String} The unique identifier of the station. You can use this as an input parameter for a rail search.
   * @param label {String} The full name of the station, in UTF-8 format.
   */
  var exports = function(value, label) {
    var _this = this;

    _this['value'] = value;
    _this['label'] = label;
  };

  /**
   * Constructs a <code>RailStationAutocompleteResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RailStationAutocompleteResponse} obj Optional instance to populate.
   * @return {module:model/RailStationAutocompleteResponse} The populated <code>RailStationAutocompleteResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
    }
    return obj;
  }

  /**
   * The unique identifier of the station. You can use this as an input parameter for a rail search.
   * @member {String} value
   */
  exports.prototype['value'] = undefined;
  /**
   * The full name of the station, in UTF-8 format.
   * @member {String} label
   */
  exports.prototype['label'] = undefined;



  return exports;
}));


