/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CarReservation', 'model/FlightReservationBound', 'model/FlightTicket', 'model/HotelReservation', 'model/OtherReservation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CarReservation'), require('./FlightReservationBound'), require('./FlightTicket'), require('./HotelReservation'), require('./OtherReservation'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.Reservation = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.CarReservation, root.AmadeusTravelInnovationSandbox.FlightReservationBound, root.AmadeusTravelInnovationSandbox.FlightTicket, root.AmadeusTravelInnovationSandbox.HotelReservation, root.AmadeusTravelInnovationSandbox.OtherReservation);
  }
}(this, function(ApiClient, CarReservation, FlightReservationBound, FlightTicket, HotelReservation, OtherReservation) {
  'use strict';




  /**
   * The Reservation model module.
   * @module model/Reservation
   * @version 1.2
   */

  /**
   * Constructs a new <code>Reservation</code>.
   * @alias module:model/Reservation
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Reservation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reservation} obj Optional instance to populate.
   * @return {module:model/Reservation} The populated <code>Reservation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('flight_tickets')) {
        obj['flight_tickets'] = FlightTicket.constructFromObject(data['flight_tickets']);
      }
      if (data.hasOwnProperty('unticketed_flights')) {
        obj['unticketed_flights'] = ApiClient.convertToType(data['unticketed_flights'], [FlightReservationBound]);
      }
      if (data.hasOwnProperty('cars')) {
        obj['cars'] = ApiClient.convertToType(data['cars'], [CarReservation]);
      }
      if (data.hasOwnProperty('hotels')) {
        obj['hotels'] = ApiClient.convertToType(data['hotels'], [HotelReservation]);
      }
      if (data.hasOwnProperty('others')) {
        obj['others'] = ApiClient.convertToType(data['others'], [OtherReservation]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/FlightTicket} flight_tickets
   */
  exports.prototype['flight_tickets'] = undefined;
  /**
   * The flight itineraries in this reservation that have not yet been ticketed or priced.
   * @member {Array.<module:model/FlightReservationBound>} unticketed_flights
   */
  exports.prototype['unticketed_flights'] = undefined;
  /**
   * The rental cars reserved.
   * @member {Array.<module:model/CarReservation>} cars
   */
  exports.prototype['cars'] = undefined;
  /**
   * The hotel room bookings in this reservation.
   * @member {Array.<module:model/HotelReservation>} hotels
   */
  exports.prototype['hotels'] = undefined;
  /**
   * Free text information to represent other travel items that may be considered part of the travel itinerary in this reservation.
   * @member {Array.<module:model/OtherReservation>} others
   */
  exports.prototype['others'] = undefined;



  return exports;
}));


