/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.RestrictedRate = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RestrictedRate model module.
   * @module model/RestrictedRate
   * @version 1.2
   */

  /**
   * Constructs a new <code>RestrictedRate</code>.
   * @alias module:model/RestrictedRate
   * @class
   * @param rateCode {String} The unique identifier of this rate.
   * @param rateName {String} The name used by the company to describe this rate.
   * @param restrictions {String} An enumeration of the type of restrictions associated with this rate.
   */
  var exports = function(rateCode, rateName, restrictions) {
    var _this = this;

    _this['rate_code'] = rateCode;
    _this['rate_name'] = rateName;
    _this['restrictions'] = restrictions;
  };

  /**
   * Constructs a <code>RestrictedRate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RestrictedRate} obj Optional instance to populate.
   * @return {module:model/RestrictedRate} The populated <code>RestrictedRate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rate_code')) {
        obj['rate_code'] = ApiClient.convertToType(data['rate_code'], 'String');
      }
      if (data.hasOwnProperty('rate_name')) {
        obj['rate_name'] = ApiClient.convertToType(data['rate_name'], 'String');
      }
      if (data.hasOwnProperty('restrictions')) {
        obj['restrictions'] = ApiClient.convertToType(data['restrictions'], 'String');
      }
    }
    return obj;
  }

  /**
   * The unique identifier of this rate.
   * @member {String} rate_code
   */
  exports.prototype['rate_code'] = undefined;
  /**
   * The name used by the company to describe this rate.
   * @member {String} rate_name
   */
  exports.prototype['rate_name'] = undefined;
  /**
   * An enumeration of the type of restrictions associated with this rate.
   * @member {String} restrictions
   */
  exports.prototype['restrictions'] = undefined;



  return exports;
}));


