/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.TopDestinationsSearchResult = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TopDestinationsSearchResult model module.
   * @module model/TopDestinationsSearchResult
   * @version 1.2
   */

  /**
   * Constructs a new <code>TopDestinationsSearchResult</code>.
   * @alias module:model/TopDestinationsSearchResult
   * @class
   * @param destination {String} The <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> of the city or airport to which the traveler may go, from the provided origin
   * @param flights {Integer} Number of flights from origin to destination during the search period provided
   * @param travelers {Integer} Number of passengers from origin to destination during the search period provided
   */
  var exports = function(destination, flights, travelers) {
    var _this = this;

    _this['destination'] = destination;
    _this['flights'] = flights;
    _this['travelers'] = travelers;
  };

  /**
   * Constructs a <code>TopDestinationsSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopDestinationsSearchResult} obj Optional instance to populate.
   * @return {module:model/TopDestinationsSearchResult} The populated <code>TopDestinationsSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('destination')) {
        obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
      }
      if (data.hasOwnProperty('flights')) {
        obj['flights'] = ApiClient.convertToType(data['flights'], 'Integer');
      }
      if (data.hasOwnProperty('travelers')) {
        obj['travelers'] = ApiClient.convertToType(data['travelers'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * The <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> of the city or airport to which the traveler may go, from the provided origin
   * @member {String} destination
   */
  exports.prototype['destination'] = undefined;
  /**
   * Number of flights from origin to destination during the search period provided
   * @member {Integer} flights
   */
  exports.prototype['flights'] = undefined;
  /**
   * Number of passengers from origin to destination during the search period provided
   * @member {Integer} travelers
   */
  exports.prototype['travelers'] = undefined;



  return exports;
}));


