/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TrainSearchSegment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TrainSearchSegment'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.TrainSearchItinerary = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.TrainSearchSegment);
  }
}(this, function(ApiClient, TrainSearchSegment) {
  'use strict';




  /**
   * The TrainSearchItinerary model module.
   * @module model/TrainSearchItinerary
   * @version 1.2
   */

  /**
   * Constructs a new <code>TrainSearchItinerary</code>.
   * @alias module:model/TrainSearchItinerary
   * @class
   * @param trains {Array.<module:model/TrainSearchSegment>} The array of trains that will be required to complete the given itinerary. Since the cache currently only contains direct itineraries, there will be only one object in this array.
   */
  var exports = function(trains) {
    var _this = this;

    _this['trains'] = trains;
  };

  /**
   * Constructs a <code>TrainSearchItinerary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainSearchItinerary} obj Optional instance to populate.
   * @return {module:model/TrainSearchItinerary} The populated <code>TrainSearchItinerary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('trains')) {
        obj['trains'] = ApiClient.convertToType(data['trains'], [TrainSearchSegment]);
      }
    }
    return obj;
  }

  /**
   * The array of trains that will be required to complete the given itinerary. Since the cache currently only contains direct itineraries, there will be only one object in this array.
   * @member {Array.<module:model/TrainSearchSegment>} trains
   */
  exports.prototype['trains'] = undefined;



  return exports;
}));


