/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RailService'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RailService'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.TrainScheduleSearchResult = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.RailService);
  }
}(this, function(ApiClient, RailService) {
  'use strict';




  /**
   * The TrainScheduleSearchResult model module.
   * @module model/TrainScheduleSearchResult
   * @version 1.2
   */

  /**
   * Constructs a new <code>TrainScheduleSearchResult</code>.
   * @alias module:model/TrainScheduleSearchResult
   * @class
   * @param originStationId {String} Station ID of the origin station for this search.
   * @param _date {Date} The search date provided in the input.
   * @param services {Array.<module:model/RailService>} Array to describe service to the destinations.
   */
  var exports = function(originStationId, _date, services) {
    var _this = this;

    _this['origin_station_id'] = originStationId;
    _this['date'] = _date;
    _this['services'] = services;
  };

  /**
   * Constructs a <code>TrainScheduleSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainScheduleSearchResult} obj Optional instance to populate.
   * @return {module:model/TrainScheduleSearchResult} The populated <code>TrainScheduleSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('origin_station_id')) {
        obj['origin_station_id'] = ApiClient.convertToType(data['origin_station_id'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('services')) {
        obj['services'] = ApiClient.convertToType(data['services'], [RailService]);
      }
    }
    return obj;
  }

  /**
   * Station ID of the origin station for this search.
   * @member {String} origin_station_id
   */
  exports.prototype['origin_station_id'] = undefined;
  /**
   * The search date provided in the input.
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * Array to describe service to the destinations.
   * @member {Array.<module:model/RailService>} services
   */
  exports.prototype['services'] = undefined;



  return exports;
}));


