/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.TravelRecordHeader = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TravelRecordHeader model module.
   * @module model/TravelRecordHeader
   * @version 1.2
   */

  /**
   * Constructs a new <code>TravelRecordHeader</code>.
   * @alias module:model/TravelRecordHeader
   * @class
   * @param creationOfficeId {String} 9 character Amadeus office identifier of the travel agency that created this travel record. An office ID may be considered as equivalent to a <a href=\"https://en.wikipedia.org/wiki/Pseudo_city_code\">PCC</a> in other reservation systems.
   * @param ownerOfficeId {String} 9 character Amadeus office identifier of the travel agency that owns and manages this travel record.
   */
  var exports = function(creationOfficeId, ownerOfficeId) {
    var _this = this;

    _this['creation_office_id'] = creationOfficeId;
    _this['owner_office_id'] = ownerOfficeId;
  };

  /**
   * Constructs a <code>TravelRecordHeader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TravelRecordHeader} obj Optional instance to populate.
   * @return {module:model/TravelRecordHeader} The populated <code>TravelRecordHeader</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('creation_office_id')) {
        obj['creation_office_id'] = ApiClient.convertToType(data['creation_office_id'], 'String');
      }
      if (data.hasOwnProperty('owner_office_id')) {
        obj['owner_office_id'] = ApiClient.convertToType(data['owner_office_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * 9 character Amadeus office identifier of the travel agency that created this travel record. An office ID may be considered as equivalent to a <a href=\"https://en.wikipedia.org/wiki/Pseudo_city_code\">PCC</a> in other reservation systems.
   * @member {String} creation_office_id
   */
  exports.prototype['creation_office_id'] = undefined;
  /**
   * 9 character Amadeus office identifier of the travel agency that owns and manages this travel record.
   * @member {String} owner_office_id
   */
  exports.prototype['owner_office_id'] = undefined;



  return exports;
}));


