/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Message', 'model/Reservation', 'model/TravelRecordHeader', 'model/Traveler'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Message'), require('./Reservation'), require('./TravelRecordHeader'), require('./Traveler'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.TravelRecordResponse = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Message, root.AmadeusTravelInnovationSandbox.Reservation, root.AmadeusTravelInnovationSandbox.TravelRecordHeader, root.AmadeusTravelInnovationSandbox.Traveler);
  }
}(this, function(ApiClient, Message, Reservation, TravelRecordHeader, Traveler) {
  'use strict';




  /**
   * The TravelRecordResponse model module.
   * @module model/TravelRecordResponse
   * @version 1.2
   */

  /**
   * Constructs a new <code>TravelRecordResponse</code>.
   * @alias module:model/TravelRecordResponse
   * @class
   * @param recordLocator {String} 6 character identifier of this travel record on the Amadeus system.
   */
  var exports = function(recordLocator) {
    var _this = this;

    _this['record_locator'] = recordLocator;




  };

  /**
   * Constructs a <code>TravelRecordResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TravelRecordResponse} obj Optional instance to populate.
   * @return {module:model/TravelRecordResponse} The populated <code>TravelRecordResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('record_locator')) {
        obj['record_locator'] = ApiClient.convertToType(data['record_locator'], 'String');
      }
      if (data.hasOwnProperty('header')) {
        obj['header'] = TravelRecordHeader.constructFromObject(data['header']);
      }
      if (data.hasOwnProperty('messages')) {
        obj['messages'] = ApiClient.convertToType(data['messages'], [Message]);
      }
      if (data.hasOwnProperty('travelers')) {
        obj['travelers'] = ApiClient.convertToType(data['travelers'], [Traveler]);
      }
      if (data.hasOwnProperty('reservation')) {
        obj['reservation'] = Reservation.constructFromObject(data['reservation']);
      }
    }
    return obj;
  }

  /**
   * 6 character identifier of this travel record on the Amadeus system.
   * @member {String} record_locator
   */
  exports.prototype['record_locator'] = undefined;
  /**
   * Summarized metadata on the record that has been retrieved.
   * @member {module:model/TravelRecordHeader} header
   */
  exports.prototype['header'] = undefined;
  /**
   * Functional or technical messages associated with the retrieval of this travel record.
   * @member {Array.<module:model/Message>} messages
   */
  exports.prototype['messages'] = undefined;
  /**
   * Information about each traveler who may be included as part of this travel record.
   * @member {Array.<module:model/Traveler>} travelers
   */
  exports.prototype['travelers'] = undefined;
  /**
   * Details about the itineraries that have been reserved as part of this travel record.
   * @member {module:model/Reservation} reservation
   */
  exports.prototype['reservation'] = undefined;



  return exports;
}));


