/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.VehicleInfo = factory(root.AmadeusTravelInnovationSandbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VehicleInfo model module.
   * @module model/VehicleInfo
   * @version 1.2
   */

  /**
   * Constructs a new <code>VehicleInfo</code>.
   * @alias module:model/VehicleInfo
   * @class
   * @param acrissCode {String} The 4 letter <a href=\"http://en.wikipedia.org/wiki/ACRISS_Car_Classification_Code\">ACRISS code</a> that defines the properties of vehicle being rented.
   * @param category {String} The decoded ACRISS vehicle category (For example&colon; Economy, Luxury, Standard).
   */
  var exports = function(acrissCode, category) {
    var _this = this;

    _this['acriss_code'] = acrissCode;
    _this['category'] = category;




  };

  /**
   * Constructs a <code>VehicleInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VehicleInfo} obj Optional instance to populate.
   * @return {module:model/VehicleInfo} The populated <code>VehicleInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('acriss_code')) {
        obj['acriss_code'] = ApiClient.convertToType(data['acriss_code'], 'String');
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('transmission')) {
        obj['transmission'] = ApiClient.convertToType(data['transmission'], 'String');
      }
      if (data.hasOwnProperty('air_conditioning')) {
        obj['air_conditioning'] = ApiClient.convertToType(data['air_conditioning'], 'Boolean');
      }
      if (data.hasOwnProperty('fuel')) {
        obj['fuel'] = ApiClient.convertToType(data['fuel'], 'String');
      }
    }
    return obj;
  }

  /**
   * The 4 letter <a href=\"http://en.wikipedia.org/wiki/ACRISS_Car_Classification_Code\">ACRISS code</a> that defines the properties of vehicle being rented.
   * @member {String} acriss_code
   */
  exports.prototype['acriss_code'] = undefined;
  /**
   * The decoded ACRISS vehicle category (For example&colon; Economy, Luxury, Standard).
   * @member {String} category
   */
  exports.prototype['category'] = undefined;
  /**
   * The decoded ACRISS vehicle type, to let you know what kind of vehicle this is (For example&colon; Van, SUV, Pickup).
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * The decoded ACRISS transmission type, to let you know if this vehicle is Automatic or Manual Transmission (stick-shift).
   * @member {String} transmission
   */
  exports.prototype['transmission'] = undefined;
  /**
   * The decoded ACRISS air_conditioning information, to let you know if this vehicle has air conditioning
   * @member {Boolean} air_conditioning
   */
  exports.prototype['air_conditioning'] = undefined;
  /**
   * The decoded ACRISS fuel type, to let you know if this vehicle is hybrid, electric, etc.
   * @member {String} fuel
   */
  exports.prototype['fuel'] = undefined;



  return exports;
}));


