/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount', 'model/Image', 'model/Rate', 'model/VehicleInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'), require('./Image'), require('./Rate'), require('./VehicleInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.AmadeusTravelInnovationSandbox) {
      root.AmadeusTravelInnovationSandbox = {};
    }
    root.AmadeusTravelInnovationSandbox.Vehicle = factory(root.AmadeusTravelInnovationSandbox.ApiClient, root.AmadeusTravelInnovationSandbox.Amount, root.AmadeusTravelInnovationSandbox.Image, root.AmadeusTravelInnovationSandbox.Rate, root.AmadeusTravelInnovationSandbox.VehicleInfo);
  }
}(this, function(ApiClient, Amount, Image, Rate, VehicleInfo) {
  'use strict';




  /**
   * The Vehicle model module.
   * @module model/Vehicle
   * @version 1.2
   */

  /**
   * Constructs a new <code>Vehicle</code>.
   * @alias module:model/Vehicle
   * @class
   * @param vehicleInfo {module:model/VehicleInfo} More information about the type of vehicle on offer.
   */
  var exports = function(vehicleInfo) {
    var _this = this;

    _this['vehicle_info'] = vehicleInfo;



  };

  /**
   * Constructs a <code>Vehicle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vehicle} obj Optional instance to populate.
   * @return {module:model/Vehicle} The populated <code>Vehicle</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('vehicle_info')) {
        obj['vehicle_info'] = VehicleInfo.constructFromObject(data['vehicle_info']);
      }
      if (data.hasOwnProperty('rates')) {
        obj['rates'] = ApiClient.convertToType(data['rates'], [Rate]);
      }
      if (data.hasOwnProperty('estimated_total')) {
        obj['estimated_total'] = Amount.constructFromObject(data['estimated_total']);
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = Image.constructFromObject(data['image']);
      }
    }
    return obj;
  }

  /**
   * More information about the type of vehicle on offer.
   * @member {module:model/VehicleInfo} vehicle_info
   */
  exports.prototype['vehicle_info'] = undefined;
  /**
   * Rates that will be applied during the duration of the car rental requested. These rates are generally not inclusive of tax and are used by the car rental company to compute the total cost at the end of the rental period.
   * @member {Array.<module:model/Rate>} rates
   */
  exports.prototype['rates'] = undefined;
  /**
   * The estimated total cost of the rental given the rental period and location provided, including all mandatory taxes and charges, and using a default set of rental options and restrictions defined by the car company.
   * @member {module:model/Amount} estimated_total
   */
  exports.prototype['estimated_total'] = undefined;
  /**
   * An image to give an indication of what to expect when renting this vehicle.
   * @member {module:model/Image} image
   */
  exports.prototype['image'] = undefined;



  return exports;
}));


