/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmadeusTravelInnovationSandbox);
  }
}(this, function(expect, AmadeusTravelInnovationSandbox) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HotelPropertyResponse', function() {
    it('should create an instance of HotelPropertyResponse', function() {
      // uncomment below and update the code to test HotelPropertyResponse
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be.a(AmadeusTravelInnovationSandbox.HotelPropertyResponse);
    });

    it('should have the property propertyCode (base name: "property_code")', function() {
      // uncomment below and update the code to test the property propertyCode
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property propertyName (base name: "property_name")', function() {
      // uncomment below and update the code to test the property propertyName
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalPrice (base name: "total_price")', function() {
      // uncomment below and update the code to test the property totalPrice
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property minDailyRate (base name: "min_daily_rate")', function() {
      // uncomment below and update the code to test the property minDailyRate
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property contacts (base name: "contacts")', function() {
      // uncomment below and update the code to test the property contacts
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property amenities (base name: "amenities")', function() {
      // uncomment below and update the code to test the property amenities
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property awards (base name: "awards")', function() {
      // uncomment below and update the code to test the property awards
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property rooms (base name: "rooms")', function() {
      // uncomment below and update the code to test the property rooms
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

    it('should have the property moreRoomsAtThisHotel (base name: "more_rooms_at_this_hotel")', function() {
      // uncomment below and update the code to test the property moreRoomsAtThisHotel
      //var instane = new AmadeusTravelInnovationSandbox.HotelPropertyResponse();
      //expect(instance).to.be();
    });

  });

}));
