/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmadeusTravelInnovationSandbox);
  }
}(this, function(expect, AmadeusTravelInnovationSandbox) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PointOfInterestResult', function() {
    it('should create an instance of PointOfInterestResult', function() {
      // uncomment below and update the code to test PointOfInterestResult
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be.a(AmadeusTravelInnovationSandbox.PointOfInterestResult);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property mainImage (base name: "main_image")', function() {
      // uncomment below and update the code to test the property mainImage
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property grades (base name: "grades")', function() {
      // uncomment below and update the code to test the property grades
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property details (base name: "details")', function() {
      // uncomment below and update the code to test the property details
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property contextualImages (base name: "contextual_images")', function() {
      // uncomment below and update the code to test the property contextualImages
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property geonameId (base name: "geoname_id")', function() {
      // uncomment below and update the code to test the property geonameId
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

    it('should have the property walkTime (base name: "walk_time")', function() {
      // uncomment below and update the code to test the property walkTime
      //var instane = new AmadeusTravelInnovationSandbox.PointOfInterestResult();
      //expect(instance).to.be();
    });

  });

}));
